# Generated by Django 4.0.6 on 2022-07-21 13:30

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gopedia_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfadmin',
            name='business_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pdfadmin',
            name='list_of_available_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
        migrations.AddField(
            model_name='pdfadmin',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pdfadmin',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 13, 30, 2, 36600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentsummarysubscriber',
            name='last_date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 13, 30, 2, 38598, tzinfo=utc), verbose_name='Recent purchase date'),
        ),
    ]
