# Generated by Django 4.0.6 on 2022-07-21 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gopedia_management', '0002_pdfadmin_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfadmin',
            name='list_of_available_courses',
        ),
        migrations.AlterField(
            model_name='pdfadmin',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 14, 26, 58, 674816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studentsummarysubscriber',
            name='last_date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 14, 26, 58, 677815, tzinfo=utc), verbose_name='Recent purchase date'),
        ),
    ]
