# Generated by Django 4.0.6 on 2022-07-22 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gopedia_management', '0003_remove_pdfadmin_list_of_available_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfadmin',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 14, 24, 36, 81435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pdfadmin',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsummarysubscriber',
            name='last_date_purchased',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 14, 24, 36, 84411, tzinfo=utc), verbose_name='Recent purchase date'),
        ),
    ]
